--- #YAML:1.0
name: WWW-Lipsum
version: 0.11
license: unrestricted
distribution_type: module
requires:
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  WWW::Lipsum:
    file: lib/WWW/Lipsum.pm
    version: 0.11
generated_by: Module::Build version 0.19
