---
abstract: 'perl interface to www.lipsum.com'
author:
  - 'Zoffix Znet <cpan@zoffix.com>'
build_requires:
  Test::More: 0
  perl: 5.006
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Lipsum
requires:
  Carp: 0
  LWP::UserAgent: 0
  Mojo::DOM: 0
  Moo: 0
  overload: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/zoffixznet/WWW-Lipsum/issues
  repository: git://github.com/zoffixznet/WWW-Lipsum.git
version: 1.001001
